version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    labels: [] # disable default labels

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels: [] # disable default labels

  - package-ecosystem: pip
    directory: "/python"
    schedule:
      interval: weekly
    labels: [] # disable default labels
